package prompts;

public enum WT2TYPES {


        AGREE_0R_DISAGREE,
        TO_WHAT_EXTENT_AGREE_OR_DISAGREE,
        DISCUSS_BOTH_VIEWS,
        DIRECT_QUESTIONS,
        CAUSE_SOLUTION,
        TO_WHAT_EXTEND_ADVANTAGES_OUTWEIGH_DISADVANTAGES
}
